# Generated by Django 5.1.3 on 2024-12-03 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, verbose_name='Ulaşım Aracı Plakası')),
                ('driver', models.CharField(max_length=80, verbose_name='Şoför Adı Soyadı')),
                ('model', models.CharField(max_length=50, verbose_name='Ulaşım Aracı Modeli')),
                ('max_passenger', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Maksimum Yolcu Sayısı')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sahibi')),
            ],
        ),
    ]
