# Generated by Django 5.1.3 on 2024-12-03 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Otel Adı')),
                ('phone', models.CharField(default='+90', max_length=13, validators=[django.core.validators.MinLengthValidator(13, 'Lütfen telefon numarasını alan kodu ile birlikte giriniz.')])),
            ],
        ),
    ]
