# Generated by Django 5.1.3 on 2024-12-04 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otel',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='otel_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
            preserve_default=False,
        ),
    ]
