# Generated by Django 5.1.3 on 2024-12-05 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0003_alter_otel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_people', models.PositiveSmallIntegerField()),
                ('max_people', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ücret (Price)')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira')], default='TRY', max_length=3)),
                ('otel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_otel', to='otel.otel', verbose_name='Otel')),
            ],
        ),
    ]
