# Generated by Django 5.1.3 on 2024-12-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0004_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('TRY', 'TRY')], default='TRY', max_length=3),
        ),
    ]
