# Generated by Django 5.1.3 on 2024-12-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otel', '0003_alter_otel_phone'),
        ('user', '0002_remove_userprofile_is_reseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_otel', to='otel.otel', verbose_name='Kayıtlı Olduğu Otel'),
        ),
    ]
