# Generated by Django 5.1.3 on 2024-12-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Yolcu Adı Soyadı')),
                ('location', models.CharField(max_length=120, verbose_name='Nereden')),
                ('destination', models.CharField(max_length=120, verbose_name='Nereye')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('time', models.TimeField(verbose_name='Saat')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_vehicle', to='vehicle.vehicle', verbose_name='Atanan Araç')),
            ],
        ),
    ]
