# Generated by Django 5.1.3 on 2024-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='surname',
            field=models.CharField(default='', max_length=80, verbose_name='Yolcu Soyadı (Passenger Surname)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Yolcu Adı (Passenger Name)'),
        ),
    ]
