# Generated by Django 5.1.3 on 2024-12-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_surname_alter_job_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(verbose_name='Tarih (Date)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='destination',
            field=models.CharField(max_length=120, verbose_name='Nereye (To)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=120, verbose_name='Nereden (From)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.TimeField(verbose_name='Saat (Time)'),
        ),
    ]
