# Generated by Django 5.1.3 on 2024-12-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_date_alter_job_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='job',
            name='passenger_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, verbose_name='Yolcu Sayısı (Passenger Count)'),
        ),
    ]
