# Generated by Django 5.1.3 on 2024-12-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_email_job_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
    ]
