# Generated by Django 5.1.3 on 2024-12-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Yolcu Email Adresi (Passenger Email Address)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Yolcu Telefon Numarası (Passenger Phone Number)'),
        ),
    ]
