# Generated by Django 5.1.3 on 2024-12-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('TRY', 'Turkish Lira')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10, verbose_name='Ücret (Price)'),
            preserve_default=False,
        ),
    ]
