# Generated by Django 5.1.3 on 2024-12-05 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_job_currency_job_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='job',
            name='surname',
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Yolcu Adı (Passenger Name)')),
                ('surname', models.CharField(max_length=80, verbose_name='Yolcu Soyadı (Passenger Surname)')),
                ('phone', models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Yolcu Telefon Numarası (Passenger Phone Number)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Yolcu Email Adresi (Passenger Email Address)')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_job', to='job.job', verbose_name='Yolculuk')),
            ],
        ),
    ]
