# Generated by Django 5.1.3 on 2024-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_email_remove_job_name_remove_job_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='migrate', max_length=80, verbose_name='Yolcu Adı (Passenger Name)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='surname',
            field=models.CharField(default='migratee', max_length=80, verbose_name='Yolcu Soyadı (Passenger Surname)'),
            preserve_default=False,
        ),
    ]
