# Generated by Django 5.1.3 on 2024-12-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_remove_passenger_email_remove_passenger_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='currency',
            field=models.CharField(max_length=3),
        ),
    ]
